### ISSUE TITLE
Credential 안 쓸때 Safari에서 fetch 안됨

### ISSUE THREAD

**Issue by sangguk2** [zoyi/simple-fetch#5]
credential 안쓸 때 지금 코드에서도 default 값이 '' (빈 스트링)이고 document에서도 안 쓰면 이렇게 설정해주라고 하는데, 이렇게 하면 Safari에서 fetch가 안 됩니다. (Chrome은 그냥 잘 되더군요)

그래서 라이브러리에 손 안대고 클라이언트에서 고치는 방법은
1. client.credentials = undefined
2. delete client.credentials

둘 중 하나로 하면 돌아가요.

default 값을  undefined로 변경해주시거나
credentials가 빈 string일 때 처리해 주면 좋을 것 같아요!

**Comment by highalps** [comment]
wow
